//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVDRentalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Notifications = new HashSet<Notification>();
            this.Sales = new HashSet<Sale>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string IDNumber { get; set; }
        public string Address { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public decimal Balance { get; set; }
        public decimal Fine { get; set; }
        public string Role { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
